version: '3.9'

services:
    # most:
    #     restart: on-failure:5
    #     image: mattermost/mattermost-preview:9.3.0
    #     container_name: dev-most
    #     links:
    #         - sia
    #     ports:
    #         - 8065:8065

    sia:
        restart: on-failure:5
        image: sealur/sia_service:0.3.2d
        container_name: dev-sia
        env_file:
            - .env
        ports:
            - 9000:9000
